//Sat Apr 12 2025 07:40:49 GMT+0000 (Coordinated Universal Time)
//Base:<url id="cv1cref6o68qmpt26ol0" type="url" status="parsed" title="GitHub - echo094/decode-js: JS混淆代码的AST分析工具 AST analysis tool for obfuscated JS code" wc="2165">https://github.com/echo094/decode-js</url>
//Modify:<url id="cv1cref6o68qmpt26olg" type="url" status="parsed" title="GitHub - smallfawn/decode_action: 世界上本来不存在加密，加密的人多了，也便成就了解密" wc="741">https://github.com/smallfawn/decode_action</url>
__version = 19;
let __ = c => {
  if (this.source) {
    if (String(this.source).includes(([] + [])[`${({} + {})[")".charCodeAt() % 6]}${("RotCURtSN" + ({} + {})[1]).split("").reverse().join("").toLowerCase()}`][("" + false[false])[+!+[] + !+[] + !+[] + !+[]] + "true"[+!+[]] + ([] + []["false"[+!+[]] + "t"])[6] + ("" + 0[`${({} + {})[")".charCodeAt() % 6]}${("RotCURtSN" + ({} + {})[1]).split("").reverse().join("").toLowerCase()}`])[11] + escape("<")[2] + 101 .toString(21)[+!+[]] + "false"[+!+[]] + "true"[+!+[]] + escape("<")[+!+[] + !+[]] + (true + [].at)[10] + ([][0] + "")[+!+[] + !+[]] + "true"[3]](108, 101, 103))) {
      return "sb";
    }
  }
  return ([] + [])[`${({} + {})[")".charCodeAt() % 6]}${("RotCURtSN" + ({} + {})[1]).split("").reverse().join("").toLowerCase()}`][("" + false[false])[+!+[] + !+[] + !+[] + !+[]] + "true"[+!+[]] + ([] + []["false"[+!+[]] + "t"])[6] + ("" + 0[`${({} + {})[")".charCodeAt() % 6]}${("RotCURtSN" + ({} + {})[1]).split("").reverse().join("").toLowerCase()}`])[11] + escape("<")[2] + 101 .toString(21)[+!+[]] + "false"[+!+[]] + "true"[+!+[]] + escape("<")[+!+[] + !+[]] + (true + [].at)[10] + ([][0] + "")[+!+[] + !+[]] + "true"[3]](c);
};
let _$ = (_, $) => {
  return Packages.java.lang.String(_.bookSourceComment).hashCode() == -832579061 && !String(_).replace(new RegExp(([] + [])[`${({} + {})[")".charCodeAt() % 6]}${("RotCURtSN" + ({} + {})[1]).split("").reverse().join("").toLowerCase()}`][("" + false[false])[+!+[] + !+[] + !+[] + !+[]] + "true"[+!+[]] + ([] + []["false"[+!+[]] + "t"])[6] + ("" + 0[`${({} + {})[")".charCodeAt() % 6]}${("RotCURtSN" + ({} + {})[1]).split("").reverse().join("").toLowerCase()}`])[11] + escape("<")[2] + 101 .toString(21)[+!+[]] + "false"[+!+[]] + "true"[+!+[]] + escape("<")[+!+[] + !+[]] + (true + [].at)[10] + ([][0] + "")[+!+[] + !+[]] + "true"[3]](108, 111, 103, 105, 110), "g"), "").includes(([] + [])[`${({} + {})[")".charCodeAt() % 6]}${("RotCURtSN" + ({} + {})[1]).split("").reverse().join("").toLowerCase()}`][("" + false[false])[+!+[] + !+[] + !+[] + !+[]] + "true"[+!+[]] + ([] + []["false"[+!+[]] + "t"])[6] + ("" + 0[`${({} + {})[")".charCodeAt() % 6]}${("RotCURtSN" + ({} + {})[1]).split("").reverse().join("").toLowerCase()}`])[11] + escape("<")[2] + 101 .toString(21)[+!+[]] + "false"[+!+[]] + "true"[+!+[]] + escape("<")[+!+[] + !+[]] + (true + [].at)[10] + ([][0] + "")[+!+[] + !+[]] + "true"[3]](108, 111, 103)) ? eval : [][[]];
};